import SwiftUI

// Generated by Supernova - do not modify manually
extension Color {
    
    static let Token = Color.TokenColor()
    
    struct TokenColor {

        // Brand

        // Primary
        let brandPrimaryDark = Color(.sRGB, red: 78/255, green: 60/255, blue: 116/255, opacity: 1) 
        let brandPrimaryMain = Color(.sRGB, red: 98/255, green: 76/255, blue: 146/255, opacity: 1) 
        let brandPrimaryLight = Color(.sRGB, red: 129/255, green: 106/255, blue: 177/255, opacity: 1) 
        let brandPrimaryStroke = Color(.sRGB, red: 98/255, green: 76/255, blue: 146/255, opacity: 0.5) 
        let brandPrimaryHover = Color(.sRGB, red: 129/255, green: 106/255, blue: 177/255, opacity: 0.12) 

        // Secondary
        let brandSecondaryDark = Color(.sRGB, red: 26/255, green: 72/255, blue: 116/255, opacity: 1) 
        let brandSecondaryMain = Color(.sRGB, red: 34/255, green: 92/255, blue: 147/255, opacity: 1) 
        let brandSecondaryLight = Color(.sRGB, red: 43/255, green: 123/255, blue: 199/255, opacity: 1) 
        let brandSecondaryStroke = Color(.sRGB, red: 34/255, green: 92/255, blue: 147/255, opacity: 0.5) 
        let brandSecondaryHover = Color(.sRGB, red: 34/255, green: 92/255, blue: 147/255, opacity: 0.12) 

        // Background
        let backgroundDefault = Color(.sRGB, red: 245/255, green: 245/255, blue: 245/255, opacity: 1) 
        let backgroundPaper = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 

        // Text
        let textPrimary = Color(.sRGB, red: 33/255, green: 37/255, blue: 41/255, opacity: 1) 
        let textSecondary = Color(.sRGB, red: 117/255, green: 117/255, blue: 117/255, opacity: 1) 
        let textTertiary = Color(.sRGB, red: 255/255, green: 255/255, blue: 255/255, opacity: 1) 
        let textDisabled = Color(.sRGB, red: 158/255, green: 158/255, blue: 158/255, opacity: 1) 
    }
}