import SwiftUI

// Generated by Supernova - do not modify manually
extension Text {

    func textStyleHeading() -> some View {
        return self
            .font(Font.custom("RobotoBold", size: 32))
    }

    func textStyleBody() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 24))
    }

    func textStyleLabel() -> some View {
        return self
            .font(Font.custom("RobotoRegular", size: 16))
    }
}
