import SwiftUI

// Generated by Supernova - do not modify manually
extension View {

    func shadowLevel1() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.15), radius: 8, x: 0, y: 4) 
    }

    func shadowLevel2() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.15), radius: 16, x: 0, y: 8) 
    }

    func shadowLevel3() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.15), radius: 32, x: 0, y: 12) 
    }

    func shadowLevel32() -> some View {
        return self.shadow(Color(.sRGB, red: 0/255, green: 0/255, blue: 0/255, opacity: 0.25), radius: 8, x: 0, y: 4) 
    }
}